#!/bin/sh

if [ -f "/System/Library/CoreServices/BridgeVersion.plist" ] || [ -d "/usr/libexec/rosetta" ]; then
	exec "$(dirname "$0")/arm64/Switcheroo" "$@"
else
	exec "$(dirname "$0")/x64/Switcheroo" "$@"
fi


